name: Build Gradle project

on:
  push:
  pull_request:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Java environment using Zulu JDK 17
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 2: Check out the source code of the repository
      - name: Checkout project sources
        uses: actions/checkout@v3.6.0

      # Step 3: Set up Gradle and build the project
      - name: Setup Gradle and build
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build

      # Step 4: Upload built JAR files as artifacts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifacts
          path: build/libs/*.jar
